### ISSUE TITLE
Consider using plugins as base save directory

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-ui-swing#41]
Right now we use [imagej.dir](https://github.com/imagej/imagej-ui-swing/blob/imagej-ui-swing-0.11.2/src/main/java/net/imagej/ui/swing/script/TextEditor.java#L1656-1657) which behaves poorly on OSX.

It might make more sense to use `IJ.app/plugins` as a short-term workaround. However this wouldn't help if someone wanted to save to `/macros`, for example.

Better long-term solution would be completing #19 and using the ImageJ 1.x dialog

**Comment by ctrueden** [comment]
Actually, I would suggest using `System.getProperty("user.home")` by default. But it's moot now that #19 is merged.
